### ISSUE TITLE
Remove Mention, 2 people messes up the bot, after some time the bot keeps repeating the same sentence over and over and i have to restart the app

### ISSUE THREAD

**Issue by ItzMeZip** [eeetem/GPT3-Discord-Bot#3]
is it possible to not mention the bot, instead you just chat on a specific channel and he will reply as soon as he detects a message.  And also when 2 or more people chats. It messes up and the bot and says the same thing on a loop. It also repeats the same thing over and over after some time when talking to him. How do you fix this?

Can you kindly help me with this?

**Comment by eeetem** [comment]
```
#if message.author == client.user:
	#	return

	#ignore everything other that a specific channel
	if str(message.channel.name) != "bot-channel":
		return


	#keep track of conversations across channels and servers
	if message.channel.id in client.channel_dict:
		message_list = client.channel_dict[message.channel.id]
	else:
		message_list = []
		client.channel_dict[message.channel.id] = message_list


	client.last_sender = message.author

	if len(message.content) > 1:
		message_list.append(message)


	#if we remember too much of discord history then it'll consume too many tokens
	if len(message_list)>6:
		message_list.pop(0)
	

	await talk(message,message_list)
```
change the on_message function to this and it should always talk in 1 channel.

it does sometimes get stuck in a loop but if you send 6 messages without @ing the bot it'll have no memory of the loop and freshly restart.
you can aswell try increasing the temperature and presence penalty in the completion request to avoid loops but that might cause issues on its own

**Comment by Gel0oo** [comment]
> 

thank you so much
