### ISSUE TITLE
Sometimes chat text won't make it to the bot

### ISSUE THREAD

**Issue by TFWol** [eeetem/GPT3-Discord-Bot#4]
I was wondering if you've seen the same issue with text not making it to the bot's console. 
It'll have no reply and then suddenly (if any lines at all) several requests will be sent to the bot at once.

**Comment by eeetem** [comment]
seems like a connection issue on your end. Either the bot hosting is slow to respond or the GPT3 API slow. I've never had the issue

**Comment by TFWol** [comment]
I have a couple of other bots without issue for other things, but not on GPT3.

I'll close the Issue and take a closer look at my network traffic.

Thanks for the input.
